apiVersion: v1
kind: Service
metadata:
  name: pwmanager-service
  namespace: pwmanager-system

spec:
  type: ClusterIP

  ports:
  - name: pwmanager
    port: 3000
    targetPort: pwmanager
  - name: pwmanager-debug
    port: 3010
    targetPort: pwmanager-debug
  - name: metrics
    port: 4000
    targetPort: metrics
  - name: metrics-debug
    port: 4010
    targetPort: metrics-debug
  - name: prometheus
    port: 4020
    targetPort: metrics-prom
